// Package sec implements a simple authentication scheme. It checks user credentials, and on successful
// check, it generates an encrypted, time limited token, that can be used for subsequent checks.
//
// It uses PAM (Pluggable Authentication Module) to check user credentials.
package sec

import (
	"bytes"
	"code.google.com/p/gopam"
	"crypto/aes"
	"crypto/cipher"
	"encoding/binary"
	"errors"
	"time"
)

const (
	renewThresholdRate          = 0.1
	invalidTokenMessage         = "Invalid token."
	invalidEncryptionKeyMessage = "Invalid encryption key."
)

var (
	// aes key and iv: valid during the time the application is running
	// update now possible only through restarting the app
	// (if want to update during run time, will need to take care about the previously issued keys, too)
	key []byte = []byte("01234567890abcdef")
	iv  []byte = []byte("01234567890abcdef")

	tokenValidity  time.Duration = 30
	renewThreshold time.Duration = 3
)

// A type that implements Config can be used to pass initialization values to the package.
type Config interface {
	AesKey() []byte     // AES key used for encryption
	AesIv() []byte      // AES iv used for encryption
	TokenValidity() int // Validity duration of the generated authentication tokens in seconds.
}

// It can be used to hold the encrypted authentication token.
type Token interface {
	Value() []byte
}

type token struct {
	user    string // username used during checking the credentials
	created int64  // creation time
	val     []byte // encrypted value
}

func (t *token) Value() []byte {
	if t.val != nil {
		return t.val
	}
	val, err := encrypt(*t)
	if err != nil {
		panic(err)
	}
	t.val = val
	return val
}

func decryptToken(v []byte) (token, error) {
	t := token{val: v}
	b, err := crypt(v)
	if err != nil {
		return t, err
	}
	userPos := len(iv) + 8
	if len(b) < userPos || !bytes.Equal(b[:len(iv)], iv) {
		return t, errors.New(invalidTokenMessage)
	}
	t.created, _ = binary.Varint(b[len(iv):userPos])
	t.user = string(b[userPos:])
	return t, nil
}

func encrypt(t token) ([]byte, error) {
	cap := len(iv) + 8 + len(t.user)
	b := make([]byte, cap, cap)
	copy(b, iv)
	binary.PutVarint(b[len(iv):], t.created)
	copy(b[cap-len(t.user):], t.user)
	return crypt(b)
}

// encryption/decryption with AES CTR
func crypt(in []byte) ([]byte, error) {
	b, err := aes.NewCipher(key)
	if err != nil {
		return nil, errors.New(invalidEncryptionKeyMessage)
	}
	s := cipher.NewCTR(b, iv)
	out := make([]byte, len(in))
	s.XORKeyStream(out, in)
	return out, nil
}

func checkCred(user, pwd string) error {
	fail := func() error { return errors.New("Authentication failed.") }
	t, s := pam.Start("", user, pam.ResponseFunc(func(style int, _ string) (string, bool) {
		switch style {
		case pam.PROMPT_ECHO_OFF, pam.PROMPT_ECHO_ON:
			return pwd, true
		default:
			return "", false
		}
	}))
	if s != pam.SUCCESS {
		return fail()
	}
	defer t.End(s)

	s = t.Authenticate(0)
	if s != pam.SUCCESS {
		return fail()
	}
	return nil
}

func validate(t token) (token, error) {
	d := time.Now().Sub(time.Unix(t.created, 0))
	if d > tokenValidity {
		return t, errors.New(invalidTokenMessage)
	}
	if d < renewThreshold {
		return t, nil
	}
	t.val = nil
	t.created = time.Now().Unix()
	return t, nil
}

// Checks if the provided username and password are correct. If yes, an authentication
// token is returned, otherwise an error.
func AuthPwd(user, pwd string) (Token, error) {
	var t token
	err := checkCred(user, pwd)
	if err != nil {
		return nil, err
	}
	t.user = user
	t.created = time.Now().Unix()
	return &t, nil
}

// Validates previously provided tokens if they didn't expire. If not, it
// returns the same token or a new one with extended expiration, so that a
// session doesn't expire due to inactivity shorter than 90% of the token
// validity period.
func AuthToken(t Token) (Token, error) {
	if t == nil {
		return nil, errors.New(invalidTokenMessage)
	}
	var (
		tc *token
		ok bool
	)
	if tc, ok = t.(*token); !ok {
		return AuthTokenBytes(t.Value())
	}
	tn, err := validate(*tc)
	return &tn, err
}

// The same as AuthToken but expects the byte representation of a token.
func AuthTokenBytes(v []byte) (Token, error) {
	t, err := decryptToken(v)
	if err == nil {
		t, err = validate(t)
	}
	return &t, err
}

// If the token was generated by package sec, GetUser returns the username
// whom the token belongs to. (Even if the token is expired.)
func GetUser(t Token) (string, error) {
	if t == nil {
		return "", errors.New(invalidTokenMessage)
	}
	if tc, ok := t.(*token); ok {
		return tc.user, nil
	}
	tc, err := decryptToken(t.Value())
	return tc.user, err
}

// Initializes sec by setting the key and iv for AES, and setting the token
// expiration period. The AES key must be set. (The token expiration's default is the quite
// useless value of 30 seconds.)
//
// Initialization must happen before the first call to the Auth* methods. Reinitializing with
// new keys will discard previously generated tokens. One process can use one 'instance' of
// the sec package.
func Init(c Config) {
	key = c.AesKey()
	iv = c.AesIv()
	tokenValidity = time.Duration(c.TokenValidity()) * time.Second
	renewThreshold = time.Duration(float64(tokenValidity) * renewThresholdRate)
}
